spring:
  datasource:
    url: jdbc:sqlserver://az204-gaurav.database.windows.net:1433;database=az204-gaurav;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: gaurav.joshi
    password: Smilings99@@
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect